# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e90d52f2cd148f209081f02454a82f2004a526e93f46021cf1d1540621a9167f71267f42b3855132a83e5ba19b7fead23381c14c6fe9b9fce2e2b70a89bfb5f5

test:
  secret_key_base: 0af6422c374350f8aa1b13777c1b60effea66a87b4c818521bc1dd5293faafde401548561f0a8cd042232bf7fad57028b2fba5f86d60a8a8a333258228a1fa48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
